ALL:
	+make -C ./bin

clean:
	rm -rf CUMC3D
	rm -rf ./bin/*.o
	rm -rf ./bin/*genmod
	rm -rf ./bin/*.mod
	rm -rf ./bin/*.f90

cleanfile:
	rm -rf ./outfile/*.dat
	rm -rf ./outfile/*.hdf5
	rm -rf ./outfile/*.mp4
	rm -f tmp.txt